FROM wata727/tflint:latest as tflint

FROM hashicorp/terraform:VERSION

ARG TERRAGRUNT

RUN apk add --update --no-cache bash git openssh ca-certificates

ADD https://github.com/gruntwork-io/terragrunt/releases/download/${TERRAGRUNT}/terragrunt_linux_amd64 /usr/local/bin/terragrunt
RUN chmod +x /usr/local/bin/terragrunt

COPY --from=tflint /usr/local/bin/tflint /usr/local/bin/tflint
RUN chmod +x /usr/local/bin/tflint

WORKDIR /apps

ENTRYPOINT []
