#!/bin/bash

# https://github.com/coinbase/terraform-landscape/issues/56#issuecomment-456427693
# export TERRAGRUNT_TFPATH="/usr/local/bin/tfbeautify"

if [[ "$1" = "plan" ]]; then
    terraform "$@" | landscape
else
    terraform "$@"
fi
