version: 2.1

# Prerequisite
# Make sure you set secret enviroment variables in CICD
# DOCKER_USERNAME
# DOCKER_PASSWORD
# API_TOKEN

# REBUILD - it has default value "false", if need rebuild the image, turn it on with value "true"

parameters:
  rebuild:
    type: string
    default: "false"

jobs:
  build:
    docker:
      - image: alpine/docker-with-buildx
    environment:
      REBUILD: << pipeline.parameters.rebuild >>
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          apk --no-cache --update add bash curl sudo jq
          # support GNU date
          apk add --update --no-cache coreutils
          echo $REBUILD
          bash ./build.sh

  scan:
    docker:
      - image: alpine/trivy
    steps:
      - checkout
      - run: |
          trivy image --format table --exit-code 1 \
             --ignore-unfixed --vuln-type os,library \
             --scanners vuln --severity CRITICAL,HIGH \
             --timeout 10m0s alpine/terragrunt

workflows:
  build:
    jobs:
      - build:
          name: build
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main

      - scan:
          requires:
            - build
          name: scan
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main

  nightly:
    triggers:
       - schedule:
           cron: "0 4 * * 0"
           filters:
             branches:
               only:
                 - master
                 - main
    jobs:
      - build:
          name: build
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
      - scan:
          requires:
            - build
          name: scan
          context:
            - Docker-Hub
          filters:
            branches:
              only:
                - master
                - main
